#!/bin/sh
#---------------------------------------------------------------------
# script to upload a file on the status website 
#---------------------------------------------------------------------
#
if [ $# -lt 3 ]
then
	echo "Error in reading arguments"
	echo "Usage: "
        echo "`basename $0:` <user@server:/path/to/logs> <microscope> <status_dir>" >&2
	echo "Aborting!"
	exit 1
fi

echo '*############################################################################*'
echo '| Locating the files                                                         |'
echo '*============================================================================*'
echo '|                                                                            |'
#
URL=$1
MICROSCOPE=$2
STATUSDIR=$3
#
if [ ! -d $STATUSDIR ]
then
	"Could not locate $STATUSDIR"
	exit 2;
fi
#
echo "Following files will be uploaded"
echo `ls -1 ${STATUSDIR}`
#

echo '|                                                                            |'
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''


echo '*############################################################################*'
echo '| Uploading the files                                                        |'
echo '*============================================================================*'
echo '|                                                                            |'
#
# sort -r ${STATUSDIR}/data.log > ${STATUSDIR}/sortdata.log
# sort -r ${STATUSDIR}/last_recorded.txt > ${STATUSDIR}/last_recorded.txt.sorted
# sort -r ${STATUSDIR}/last_imported.txt > ${STATUSDIR}/last_imported.txt.sorted
# sort -r ${STATUSDIR}/last_processed.txt > ${STATUSDIR}/last_processed.txt.sorted
# sort -r ${STATUSDIR}/last_errors.txt > ${STATUSDIR}/last_errors.txt.sorted
#
#linenum=70000
linenum=40000
tail -n ${linenum} ${STATUSDIR}/data.log | sort -r > ${STATUSDIR}/sortdata.log
tail -n ${linenum} ${STATUSDIR}/last_recorded.txt | sort -r > ${STATUSDIR}/last_recorded.txt.sorted
tail -n ${linenum} ${STATUSDIR}/last_imported.txt | sort -r > ${STATUSDIR}/last_imported.txt.sorted
tail -n ${linenum} ${STATUSDIR}/last_processed.txt | sort -r > ${STATUSDIR}/last_processed.txt.sorted
tail -n ${linenum} ${STATUSDIR}/last_errors.txt | sort -r > ${STATUSDIR}/last_errors.txt.sorted
#
cd ${STATUSDIR}

scp last.txt ${URL}/logs/${MICROSCOPE}.last
scp last_recorded.txt.sorted ${URL}/logs/${MICROSCOPE}.last_recorded
scp last_imported.txt.sorted ${URL}/logs/${MICROSCOPE}.last_imported
scp last_processed.txt.sorted ${URL}/logs/${MICROSCOPE}.last_processed
scp last_errors.txt.sorted ${URL}/logs/${MICROSCOPE}.last_errors
scp sortdata.log ${URL}/logs/${MICROSCOPE}.data

scp 1-FFT.jpg ${URL}/thumbnails/${MICROSCOPE}-1-FFT.jpg
scp 1-image.jpg ${URL}/thumbnails/${MICROSCOPE}-1-image.jpg
scp 2-FFT.jpg ${URL}/thumbnails/${MICROSCOPE}-2-FFT.jpg
scp 2-image.jpg ${URL}/thumbnails/${MICROSCOPE}-2-image.jpg
scp 3-image.png ${URL}/thumbnails/${MICROSCOPE}-3-image.png
scp 4-image.jpg ${URL}/thumbnails/${MICROSCOPE}-4-image.jpg
scp 6-AverageImage.jpg ${URL}/thumbnails/${MICROSCOPE}-6-AverageImage.jpg
scp 7-PS.jpg ${URL}/thumbnails/${MICROSCOPE}-7-PS.jpg
scp 8-PSdriftcor.jpg ${URL}/thumbnails/${MICROSCOPE}-8-PSdriftcor.jpg


echo '|                                                                            |'
echo '*============================================================================*'
echo ''
echo ''
echo ''
echo ''

